name: Docker

on:
  push:
    branches:
      - main

  pull_request:

env:
  IMAGE_NAME: json
  MAJOR_VERSION: 11

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: MAJOR_VERSION=${{ env.MAJOR_VERSION }}
          load: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Test
        run: cat test.json | docker run -i --rm ${{ env.IMAGE_NAME }} -ag name value

  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: MAJOR_VERSION=${{ env.MAJOR_VERSION }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR_VERSION }}
            ghcr.io/chorrell/${{ env.IMAGE_NAME }}:latest
            ghcr.io/chorrell/${{ env.IMAGE_NAME }}:${{ env.MAJOR_VERSION }}
