name: Docker

on:
  push:
    branches:
      - master

  pull_request:

env:
  IMAGE_NAME: json
  MAJOR_VERSION: 10

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Test
        run: cat test.json | docker run -i --rm $IMAGE_NAME -ag name value

  # Push image to GitHub Container Registry
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg MAJOR_VERSION=$MAJOR_VERSION

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/$GITHUB_ACTOR/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID:$MAJOR_VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          
          docker push $IMAGE_ID:$MAJOR_VERSION
          docker push $IMAGE_ID:latest
          
